######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 18 14:51:29 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += client.h
SOURCES += client.cpp
