######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 20 11:18:29 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += server.h
SOURCES += server.cpp
